### ISSUE TITLE
GDM: "Unable to determine if can activate sessions" with GDM 41.3 and ConsoleKit2 1.2.4

### ISSUE THREAD

**Issue by neelchauhan** [ConsoleKit2/ConsoleKit2#129]
I am attempting to update GDM to 41.3 on FreeBSD (from 3.28.4) and am running into this issue:

    gdm 5470 - - GLib-GIO: g_dbus_connection_call_sync_internal: assertion 'object_path != NULL && g_variant_is_object_path (object_path)' failed
    gdm 5470 - - Gdm: Unable to determine if can activate sessions: 
    gdm 5470 - - GLib: g_error_free: assertion 'error != NULL' failed

The code giving me an issue looks like this:

    #elif defined(WITH_CONSOLE_KIT)
            gboolean ret;
    
            reply = g_dbus_connection_call_sync (connection,
                                                 CK_NAME,
                                                 seat_id,
                                                 CK_SEAT_INTERFACE,
                                                 "CanActivateSessions",
                                                 NULL,
                                                 G_VARIANT_TYPE ("(b)"),
                                                 G_DBUS_CALL_FLAGS_NONE,
                                                 -1,
                                                 NULL, &local_error);
         if (reply == NULL) {
                    g_warning ("Unable to determine if can activate sessions: %s", local_error ? local_error->message : "");
                    g_error_free (local_error);
                    return FALSE;
            }
    
Source: https://reviews.freebsd.org/D34088 (file `x11/gdm/files/patch-common_gdm-common.c` lines 438-460).

As FreeBSD doesn't have `systemd` and needs ConsoleKit2, I copied the code from OpenBSD, where the original patches (presumably) works fine.

**Comment by ajacoutot** [comment]
Hi. OpenBSD is using this fork which has all patches integrated:
https://github.com/rnagy/gdm

Current OpenBSD port is: https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/x11/gnome/gdm/

**Comment by neelchauhan** [comment]
Yes, I know about the OpenBSD fork, which is where I got my patches from. :-)

Even if I used the OpenBSD fork directly, I still get the same error.

**Comment by ajacoutot** [comment]
@rnagy does this ring a bell to you?

**Comment by neelchauhan** [comment]
I have some good news: In my patch, I had to put the activate session code causing the issue in #ifdefs and it works. Closing the ticket.

It's an "ugly" solution but it's what I had to do and it works.

**Comment by rnagy** [comment]
Hi

I can look later at FreeBSD, but the code should work fine there as well, unless some other component is outdated. Why don't you just use the git repository directly instead of applying all the patches and carrying
them in the freebsd ports tree? It makes no sense.

**Comment by neelchauhan** [comment]
I got gdm 41.3 working on FreeBSD.

Yes, I know I *could* use the git repository directly, but I don't believe that's the norm in the FreeBSD world for a project like GNOME (as opposed to something on GitHub).

You don't have to look at it, @rnagy. If you want to, sure look at it, but I don't want to waste your time.
