### ISSUE TITLE
ConsoleKit2 and bluez

### ISSUE THREAD

**Issue by dflogeras** [ConsoleKit2/ConsoleKit2#53]
Hi, I use Gentoo, and recently have been toying with the new plasma5 desktop.  Installing this required me to upgrade to ConsoleKit-1.0.0 (well, technically choosing sddm required that).

I have noticed that since moving from legacy to ck-1.0.0, my user can no longer access my bluez devices.  After reading the /etc/dbus-1/system.d/bluetooth.conf, I can work around this issue by adding myself to the plugdev group, but there is another entry that allows logins where at_console="true", which is how I assumed it used to work (I didn't need to be in the plugdev group before).

Is there something I am missing?  Is this a bug, or should I just add my user to the specified group and leave it as is?

**Comment by EricKoegel** [comment]
Ah, this might have to do with us no longer providing the pam at_console workaround? It was causing race conditions on some systems. Will have to look into this more.

**Comment by dflogeras** [comment]
I don't know if this information is useful or not, but on the affected machine, I temporarily installed systemd/logind when I was hitting issue #57 and noticed that I did not require the plugdev group workaround to access bluez.

So that means that either a) systemd still does the pam way (which if I understand is not the right way, at least according to RH https://lists.fedoraproject.org/pipermail/devel/2014-May/199004.html),

or b) uses some unknown to me new-fangled way of getting dbus permissions.

**Comment by dflogeras** [comment]
OK, the plot thickens.  I installed consolekit-1.0.1 this morning and no longer need the plugdev group workaround.  Either something you did between 1.0.0->1.0.1 changed the behaviour, or something the way gentoo packages it changed.  I did notice that they now install a file called pam-foreground-comat.ck.  I have no idea what it is, but I see that it is different than with 1.0.0 packaging.

**Comment by dflogeras** [comment]
Gentoo confirmed that they fixed/worked around the issue.  I am not clear if this is a interim thing, or proper; that's for you to decide :)

https://bugs.gentoo.org/show_bug.cgi?id=571524

**Comment by EricKoegel** [comment]
In dbus, it uses the systemd library call to determine if the user has at least one physical seat.
http://cgit.freedesktop.org/dbus/dbus/tree/dbus/dbus-userdb-util.c#n41
Looks like there was talk of dropping at_console in dbus but that never happened:
http://lists.freedesktop.org/archives/dbus/2009-August/011651.html
So unless someone gets to it before I do, I'll look into having dbus read the consolekit database instead of the /var/run/console/<USER> at which point the workaround won't be needed anymore.

**Comment by EricKoegel** [comment]
So I wrote a patch to dbus and submitted it(1), but the at_console policy is being deprecated in dbus(2) so there's no reason to clean it up and continue. That means the pam-forground-compat script will be an acceptable workaround until all services migrate away from the at_console policy. It looks like BlueZ and wicid might be the two big consumers of that policy.

I'm going to mark this bug closed.

1) https://bugs.freedesktop.org/show_bug.cgi?id=94591
2) https://bugs.freedesktop.org/show_bug.cgi?id=39611
