### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by alienbob** [ConsoleKit2/ConsoleKit2#62]
Guys,

One month ago I finished the dutch (nl) translation, it is available at https://www.transifex.com/consolekit2/consolekit2/language/nl/ but I noticed that it still has not been merged.
Can you please add the dutch translation to ConsoleKit2?

Thanks, Eric

**Comment by EricKoegel** [comment]
It should be pushed now. I need to fix the translation bot and then I'll let it auto-update things again.
