### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by udeved** [ConsoleKit2/ConsoleKit2#64]
Hi Eric,
short question, I am slightly confused with the versions.

You released 1.1.0, and now 1.0.2.
Is this a mistake, and it should be 1.2.0?

**Comment by EricKoegel** [comment]
Sorry for the confusion, 1.1.0 is a dev release adding new features (the xdg runtime dir support in this case) that could use more testing before a 1.2.0 stable (with odd middle numbers being development branches and even middle numbers being stable).
1.0.2 continues the 1.0 stable branch and only backported the bug fixes.

**Comment by udeved** [comment]
I see, so I'll "skip" this release, since we got 1.1.0 in unstable repo. 
Thanks!

**Comment by EricKoegel** [comment]
Marking issue closed.
