### ISSUE TITLE
On Freebsd, X11 sessions are often not activated [patch]

### ISSUE THREAD

**Issue by Victor-Bergman** [ConsoleKit2/ConsoleKit2#71]
On Freebsd (10.3), quite often X11 sessions do not become active.  If they are active, switching the virtual console and then later return to X causes the X session to be inactive.  I believe this has something to do with how the FreeBSD sc/vt drivers initialize the devices (and when).  I have a patch to fix the issue attached.  This problem is present all the way back to version 0.45.  I noticed that some time ago, someone tried to fix this issue by using /dev/consolectl, but this device is never used because isatty() is false on /dev/consolectl.  I have an attached patch that gets ConsoleKit to use /dev/consolectl and now session activation and VT switching work.

[freebsd.patch.txt](https://github.com/ConsoleKit2/ConsoleKit2/files/340314/freebsd.patch.txt)

**Comment by EricKoegel** [comment]
Thanks! I pushed it to master. You can always submit patches like these as a github pull request if you like.
