### ISSUE TITLE
When functions return NULL

### ISSUE THREAD

**Issue by konsolebox** [ConsoleKit2/ConsoleKit2#74]
Tools like ck-launch-session and pam_ck_connector.so probably should check whether functions like `ck_connector_get_runtime_dir()` return `NULL`.  Perhaps bail out or write an error message to syslog when it happens.  `setenv()` crashes when the second argument is `NULL`, and `snprintf()` sets a value of `"(null)"` for `%s`.

**Comment by EricKoegel** [comment]
I pushed the referenced commit to prevent the NULLs, additionally it was caused by the runtime dir function not happening for root but that's been changed so it shouldn't be NULL any more.
