### ISSUE TITLE
console-kit-daemon[2191]: WARNING: Couldn't read /proc/'PID'/environ: Failed to open file '/proc/'PID'/environ': No such file or directory

### ISSUE THREAD

**Issue by darkshram** [ConsoleKit2/ConsoleKit2#79]
I have replaced ConsoleKit with ConsoleKit2 in a _non-systemd_ custom Linux distro and **everything seems to works fine**. There is only one warning in the syslog that also appeared too with ConsoleKit 0.4.x:

`Sep 11 16:18:04 buildserver console-kit-daemon[2191]: WARNING: Couldn't read /proc/2342/environ: Failed to open file '/proc/2342/environ': No such file or directory`

In this case 2342 was at-spi-bus-launcher but may happen _ramdomly_ with other programs (like nm-applet) while starting graphical session:
`builduser  2342  0.0  0.1 350620  5988 ?        Sl   16:19   0:00 /usr/libexec/at-spi-bus-launcher`

Appears every time a user logs in. This warning in the _syslog_ has been around for [nearly 10 years](https://www.google.com.mx/search?q=console-kit-daemon+WARNING:+Couldn%27t+read+/proc+environ:+Failed+to+open+file).

So far, it has been (for me) a harmless warning.

**Comment by burunduk3** [comment]
I have a similar problem (**gentoo**, non-systemd, syslog is overflooded with `console-kit-daemon WARNING: Couldn't read /proc/6662/environ: Failed to open file “/proc/6662/environ”: No such file or directory`) and fix didn't work.

Looks like that there is one more line to replace `g_warning` with `d_debug`: https://github.com/ConsoleKit2/ConsoleKit2/blob/master/src/ck-sysdeps-linux.c#L564
