### ISSUE TITLE
Freebsd 11 no active session.

### ISSUE THREAD

**Issue by jsm222** [ConsoleKit2/ConsoleKit2#85]
Also noted at  [bugs.freebsd.org](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=202269#c3)
from within ck-launch-session (X11) ck-list-sessions: 
Session1:
        unix-user = '1001'
        realname = 'User'
        seat = 'Seat2'
        session-type = ''
        **active = FALSE**
        x11-display = ':0'
        x11-display-device = ''
        display-device = 'ttyv1'
        remote-host-name = ''
        is-local = TRUE
        on-since = '2016-10-09T21:04:12.703487Z'
        login-session-id = ''
        XDG_RUNTIME_DIR = '/usr/local/var/run/user/1001'
It works correctly using the "slim" display manager. Startx and xdm does not work.

**Comment by EricKoegel** [comment]
Thanks for pointing me to your diff, sorry it took so long for me to add it.
