### ISSUE TITLE
1.1.1 bugfix release?

### ISSUE THREAD

**Issue by dflogeras** [ConsoleKit2/ConsoleKit2#88]
Hey again, is there a 1.1.1 planned?  I notice some code checked in last April that might get rid of a ck-remove-directory trap I'm seeing in dmesg (plus many other little fixes).

**Comment by joakim-tjernlund** [comment]
Yes, same here. Please do a 1.1.1

**Comment by EricKoegel** [comment]
Done! https://github.com/ConsoleKit2/ConsoleKit2/releases/tag/1.1.1 Feel free to send the bug reports in.

**Comment by dflogeras** [comment]
Thanks Eric!
