### ISSUE TITLE
errors after update to last changes

### ISSUE THREAD

**Issue by idanielblake** [ConsoleKit2/ConsoleKit2#92]
console-kit-daemon[19058]: GLib-GObject-CRITICAL: g_object_ref: assertion 'object->ref_count > 0' failed
onsole-kit-daemon[19058]: GLib-GObject-CRITICAL: g_object_unref: assertion 'object->ref_count > 0' failed

**Comment by EricKoegel** [comment]
Can you kill console-kit-daemon and then run it with G_DEBUG=fatal_warnings console-kit-daemon? That should cause it to abort on the assert and then you can post a backtrace so we can find out where that's happening. Thanks.

**Comment by idanielblake** [comment]
I got those errors on logout. I'm on runit. So I change service exec line to exec env G_DEBUG=fatal_warnings console-kit-daemon and restarted the service. Now on login I get this:
kernel:[15595.031290] traps: ck-collect-sess[17233] trap int3 ip:7fcbf30d9221 sp:7fff14a0a670 error:0
and can't login anymore. Thank you

**Comment by EricKoegel** [comment]
Sorry about the login issue, I didn't intend for it to be more than a quick check. Can you try out the patch referenced above and see if that fixes the warnings on logout?

**Comment by idanielblake** [comment]
That patch fixed it. Thank you for support
