### ISSUE TITLE
udevd warnings at boot

### ISSUE THREAD

**Issue by idanielblake** [ConsoleKit2/ConsoleKit2#93]
`udevd RUN{builtin}: 'udev-acl' unknown /usr/lib/udev/rules.d/73-udev-seat-lat-rules:12`

I have compiled Consolekit with acl enabled and /usr/lib/udev/udev-acl is present:

`    ./configure \                                                                                                                                     
        --prefix=/usr \
        --sysconfdir=/etc \
        --sbindir=/usr/bin \
        --with-rundir=/run \
        --libexecdir=/usr/lib/consolekit \
        --localstatedir=/var \
        --enable-polkit \
        --enable-pam-module \
        --enable-udev-acl \
        --disable-docbook-docs \
        --with-dbus-services=/usr/share/dbus-1/services \
        --with-xinitrc-dir=/etc/X11/xinit/xinitrc.d \
        --with-pam-module-dir=/usr/lib/security \
        --without-systemdsystemunitdir \
        --disable-cgroups`

**Comment by EricKoegel** [comment]
Hey, good catch. We aren't using the seat late rules from systemd as the udev-acl program handles everything so far.
