### ISSUE TITLE
Unable to build on the armhf architecture

### ISSUE THREAD

**Issue by PureTryOut** [ConsoleKit2/ConsoleKit2#96]
I'm trying to package ConsoleKit2 1.2.0 for Alpine Linux.
Building on x86_64 works fine, but on armhf it fails.

```
configure.ac:33: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

My `./configure` command:

```
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-static
```

If I remove `AC_DISABLE_STATIC` from `configure.ac`, the error is gone.

**Comment by EricKoegel** [comment]
I don't have any arm hardware to test compiling with, can you try this patch out?

As a side note, the AC_DISABLE_STATIC commit[1] is 11 years old and Gentoo at least has some support for CK2 on arm: https://packages.gentoo.org/packages/sys-auth/consolekit Did previous versions compile for you? If they did, can you still compile them with your setup now? I don't mind pushing this patch if it works either way, just wondering what caused this to surface.

[1] https://github.com/ConsoleKit2/ConsoleKit2/commit/c6cd8d7c66b2bd39edf7ca70948982a553128282

**Comment by PureTryOut** [comment]
I guess their arm is different from armhf (which in case of Alpine means both armv6 and armv7 iirc). No, previous versions have not worked.

Your patch fixed it, thanks!
